workflows:
  ios-workflow:
    name: MonPlayer iOS Build
    max_build_duration: 60
    
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor
          
      - name: Get Flutter dependencies
        script: |
          flutter pub get
          
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
          
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos
          
      - name: Build Unsigned iOS App
        script: |
          # Compile sans signature
          flutter build ios --release --no-codesign
          
          # Prépare le fichier IPA (Payload) pour Sideloadly / AltStore
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -qr MonPlayer-Unsigned.ipa Payload
    
    artifacts:
      - build/ios/iphoneos/MonPlayer-Unsigned.ipa
    
    publishing:
      email:
        recipients:
          - midogiova@gmail.com
        notify:
          success: true
          failure: true
